# Generated by Django 2.0.4 on 2018-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0002_auto_20180419_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image4',
            field=models.ImageField(upload_to=''),
        ),
    ]
