# Generated by Django 2.0.4 on 2018-04-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0003_auto_20180420_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image4',
        ),
    ]
