# Generated by Django 2.0.4 on 2018-04-19 21:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0004_auto_20180420_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image1',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
