# Generated by Django 2.0.4 on 2018-04-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0006_auto_20180421_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomTypes',
            new_name='RoomType',
        ),
    ]
