# Generated by Django 2.0.4 on 2018-04-21 12:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0007_auto_20180421_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
