# Generated by Django 2.0.4 on 2018-04-23 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rating'),
        ),
    ]
