# Generated by Django 2.0.4 on 2018-04-23 22:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0013_customer_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image4',
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(blank=True, to='djangotest.Image'),
        ),
    ]
