# Generated by Django 2.0.4 on 2018-04-26 18:59

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0016_auto_20180425_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangotest.RoomType', verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='image',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangotest.RoomType', verbose_name='Room Type'),
        ),
    ]
