# Generated by Django 2.0.4 on 2018-04-27 18:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangotest', '0017_auto_20180426_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='From')),
                ('end', models.DateField(verbose_name='To')),
                ('bill', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='airConditioning',
            field=models.BooleanField(default=False, verbose_name='Air Conditioning'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='freeBreakfast',
            field=models.BooleanField(default=False, verbose_name='Free Breakfast'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='laundaryService',
            field=models.BooleanField(default=False, verbose_name='Laundary Service'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='minibar',
            field=models.BooleanField(default=False, verbose_name='Mini Bar'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='roomService',
            field=models.BooleanField(default=False, verbose_name='Room Service'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='WiFi'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangotest.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
